### ISSUE TITLE
BLOSS@M demo client

### ISSUE THREAD

**Issue by nikitawootten-nist** [usnistgov/blossom-dashboard#4]
A rough client UI for submitting test transactions.

![image](https://user-images.githubusercontent.com/63109766/148434162-9ad9077c-67a4-40ec-ae0e-01e66dae2704.png)
(image from @joshua-roberts)

- A hardcoded dropdown of all smart contract functions
- Select chaincode function and text fields appear for function args
- Click submit to submit transaction using node server
- Transaction output is displayed in some text area
- User should be able to select which member and client identity they are submitting the transaction as. (depends on #5)
- For the purposes of the upcoming demo, a "reset" button to remove an organization's ATO status might also be required,

**Comment by JustKuzya** [comment]
I think this can be considered done. The only thing left is to file pull request and merge branch into the main.

**Comment by iMichaela** [comment]
@JustKuzya -- Please submit then the PR?
